import { Team } from './entities/team.entity';

export const teams: Team[] = [
  {
    id: 1,
    name: 'River Plate',
    points: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalsDifference: 0,
  },
  {
    id: 2,
    name: 'Racing Club',
    points: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalsDifference: 0,
  },
  {
    id: 3,
    name: 'Defensa y Justicia',
    points: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalsDifference: 0,
  },
  {
    id: 4,
    name: 'Independiente',
    points: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalsDifference: 0,
  },
  {
    id: 5,
    name: 'San Lorenzo',
    points: 0,
    played: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalsDifference: 0,
  },
];
