import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Standing } from '../schemas/standing.schema';

@Injectable()
export class StandingSeederService {
  constructor(
    @InjectModel('Standing') private readonly standingModel: Model<Standing>,
  ) {}

  async seedStandings(): Promise<{
    status: number;
    message: string;
    data: Standing[] | null;
  }> {
    const standingsData = [
      {
        teamId: 3,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095240/info-liga-argentina/8fde64661515dd486ac91de9a42eee8d.webp',
        name: 'Argentinos',
        position: 1,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 25,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095238/info-liga-argentina/82292827507d055b2ab919e90271ba76.webp',
        name: 'Atl Tucuman',
        position: 2,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 3,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095240/info-liga-argentina/4b2b2f4ac283b5f331be6a34e396ce81.webp',
        name: 'Banfield',
        position: 3,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 82,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095240/info-liga-argentina/d26f18ad5aa7f0cf6b2811e485030e42.webp',
        name: 'Barracas Central',
        position: 4,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 26,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095238/info-liga-argentina/7b7362f2c4aecfc1eb5cd2d39536624c.webp',
        name: 'Belgrano',
        position: 5,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 6,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095240/info-liga-argentina/ad45f3c21308cf866513d32e9ccacfb9.webp',
        name: 'Boca Juniors',
        position: 6,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 78,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/eefe5f02d80cf05add72e94a96ff2f4d.webp',
        name: 'Central Cba (SdE)',
        position: 7,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 29,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095238/info-liga-argentina/35c2306e118790ba064913a15a8b8b2e.webp',
        name: 'Def y Justicia',
        position: 8,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 8,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095240/info-liga-argentina/8761b0b7deb20a3b767ae569dec81cef.webp',
        name: 'Estudiantes (LP)',
        position: 9,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 9,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095240/info-liga-argentina/46d7c397d066b061555b184ddb761067.webp',
        name: 'Gimnasia (LP)',
        position: 10,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 10,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095241/info-liga-argentina/b4b5ba8b6c0ecd06914f5a0c22b72808.webp',
        name: 'Godoy Cruz',
        position: 11,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 11,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095241/info-liga-argentina/e3df4bef3521c9bdf00570be4dae74ba.webp',
        name: 'Huracan',
        position: 12,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 32,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/633a652a03c398b0b3bb97af85c241d3.webp',
        name: 'Ind Rivadavia',
        position: 13,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 12,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095241/info-liga-argentina/9835a1c5ca932deff17ad74f3319b9e6.webp',
        name: 'Independiente',
        position: 14,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 33,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/d003a0125009b6015a2624c44cfb205f.webp',
        name: 'Instituto',
        position: 15,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 13,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095241/info-liga-argentina/4c5bd58e39bb4e69671425f24f7d3c64.webp',
        name: 'Lanus',
        position: 16,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 14,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095241/info-liga-argentina/2e5cef52e00ba0edda1189e0b238573b.webp',
        name: 'Newells',
        position: 17,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 45,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/ae8f30e6385dbcfbab6015787df9cff7.webp',
        name: 'Platense',
        position: 18,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 17,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095241/info-liga-argentina/aa3d0c0836959f0fba94dc08496c2c72.webp',
        name: 'Racing Club',
        position: 19,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 123,
        name: 'Riestra',
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095240/info-liga-argentina/a65736e3e1aea3faef905fc17321bcad.webp',
        position: 20,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 18,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095241/info-liga-argentina/b7eca3f70340e2b5fce50c87df46a267.webp',
        name: 'River Plate',
        position: 21,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 35,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/f5edb64a0a7b7a113ba5be321d817940.webp',
        name: 'Rosario Central',
        position: 22,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 19,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095238/info-liga-argentina/37d62f5e4664c6535e2c41a53d20e09f.webp',
        name: 'San Lorenzo',
        position: 23,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 81,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/a84dff2b950f26160bfff14722be7594.webp',
        name: 'Sarmiento (J)',
        position: 24,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 52,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/adb0689fdd2d664681234e285349cab2.webp',
        name: 'Talleres (C)',
        position: 25,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 20,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095238/info-liga-argentina/7eb0c8caafc203a369e2511feeecb887.webp',
        name: 'Tigre',
        position: 26,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 39,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095239/info-liga-argentina/17507d4c11f7c93af00df86d9fee6f97.webp',
        name: 'Union',
        position: 27,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
      {
        teamId: 21,
        badge:
          'https://res.cloudinary.com/dsg5ofk4e/image/upload/v1708095238/info-liga-argentina/cf67691e7782efc492772ad9ee0ab09c.webp',
        name: 'Velez',
        position: 28,
        points: 0,
        played: 0,
        wins: 0,
        draws: 0,
        losses: 0,
        goalsFor: 0,
        goalsAgainst: 0,
        goalsDifference: 0,
      },
    ];

    try {
      await this.standingModel.deleteMany({});
      await this.standingModel.insertMany(standingsData);
      return {
        status: 201,
        message: 'Standings seeded successfully.',
        data: standingsData,
      };
    } catch (error) {
      console.error(error);
      return {
        status: 500,
        message: 'Error seeding standings.',
        data: null,
      };
    }
  }
}
